language: php
php: 
  - 7.1

install: 
  - composer self-update
  - composer install
  - composer require codeclimate/php-test-reporter:dev-master

before_script: mkdir -p build/logs

script: phpunit --configuration ./phpunit.xml --coverage-clover ./build/logs/clover.xml

after_success:
  - CODECLIMATE_REPO_TOKEN=9c88c09bf1a609cda6e3c521198cfd50b2e8f23c2ab1ae6fa1fd86622dbabb51 ./vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"